-- Las cuentas de prueba (admin, PM, cliente) se crean y mantienen con
-- scripts/reset-test-accounts.ts (npx tsx scripts/reset-test-accounts.ts).
-- Este archivo se conserva como placeholder por si se requieren seeds SQL
-- adicionales que no dependan del cliente Prisma.
